config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'pages/home'
  root 'pages#home'
  get '/store', to: 'pages#store'
  get '/working', to: 'pages#working'
  get '/terms', to: 'pages#terms'
  get '/privacy', to: 'pages#privacy'
  get '/cfstore', to: 'pages#cfstore'
  get '/cfindex', to: 'pages#cfindex'

  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'

  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'

  get '/dashboard', to: 'orders#index', as: :dashboard

  resources :brands
  resources :products
 	resources :custom_orders

  resources :conversations do
    resources :messages
  end

end

app/models/order.rb
class Order < ApplicationRecord

  has_many :items, class_name: 'OrderItem'

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :authenticate_user!

	def index
		@orders = Order.all
		@custom_orders = CustomOrder.all
		@users = User.all
	end

	def new
		@order = current_cart.order
		@order.name = current_user.name
		@order.email = current_user.email
	end

	def create
		@order = current_cart.order

		if @order.update(order_params)
			session[:cart_token] = nil
			redirect_to dashboard_path
		else
			redirect_to 'new'
		end	
	end

	private

		def order_params
			params.require(:order).permit(:name, :street, :door, :city, :zipcode, :phone, :order_icon, :order_msg, :email)			
		end

end

app/views/orders/index.html.erb
<div class="row home_top_margin">
  <%= image_tag("1_1.jpg", :class => "col col-md-4 column_width_manager d-none d-sm-block col-sm-4") %>  
  <%= image_tag("1_3.jpg", :class => "col col-md-4 column_width_manager") %>
  <%= image_tag("2_1.jpg", :class => "col col-md-4 column_width_manager d-none d-sm-block col-sm-4") %>
</div>


<div class="row">
	<div align="center" class="col-md-12">
		<h1 class="mt-3">Dashboard</h1>		
	</div>
</div>

<hr>

<!-- ======================= Block Menu ======================= -->

<div class="row">

	<div class="col-md-4">
			<div class="greybox1 p-5">
				<div class="row">
				
					<div class="col-md-2">
						<i class="material-icons md-36">shopping_cart</i>		
					</div>
				
					<div align="center" class="col-md-10">
						<h3><strong>Shop Products</strong></h3>
					</div>

				</div>
		
				<hr>
		
				<p> Choose from a list of exciting weekly products, handpicked to reflect the best of the latest season. </p>

				<hr>

				<%= link_to "Try & Buy Products", store_path, class: "btn btn-drop btn-lg btn-block " %>
	
		</div>
	</div>

	<div class="col-md-4">
			<div class="p-5">
				<div class="row">
				
					<div class="col-md-2">
						<i class="material-icons md-36">message</i>		
					</div>
				
					<div align="center" class="col-md-10">
						<h3><strong>My Messages</strong></h3>
					</div>

				</div>
		
				<hr>
		
				<p> Start a conversation with us to get help, recommendations, and other exiting offers tailored just for you. </p>

				<hr>
     
		    <%= link_to "Message Now", conversations_path(sender_id: current_user.id, recipient_id: User.find_by_email("admin@dropalley.com").id), method: "post", class: "btn btn-drop btn-block btn-lg"%>
		      
	
			</div>
	</div>

	<div class="col-md-4">
			<div class="greybox2 bottom-border p-5">
				<div class="row">
				
					<div class="col-md-2">
						<i class="material-icons md-36">loyalty</i>		
					</div>
				
					<div align="center" class="col-md-10">
						<h3><strong>Custom Trials</strong></h3>
					</div>

				</div>
		
				<hr>
		
				<p> Select any product from a brand's site from the "Shop Brands" page, then request for a custom try and buy. </p>

				<hr>

				<%= link_to "Browse Brands", brands_path, class: "btn btn-drop btn-lg btn-block " %>
	
		</div>
	</div>

</div>

<!-- ======================= Block Menu ======================= -->

<div class="row mt-5">

  <div align="center" class="col-md-4 offset-md-4">
  	<i class="material-icons md-48">expand_more</i>
  </div>

</div>



<!-- ======================= Instant Try & Buy List ======================= -->

<div class="row">
	<div align="left" class="col-md-12">
		<h1>Instant Try & Buy Orders</h1>		
	</div>
</div>

<hr>

<div class="row mb-5">
	
	<% @orders.each do |order| %>
		<% if current_user.email == order.email %>	
			
			<div class="col-md-4 mt-3">
				<div class="outerbox_orderlist p-3">
					
					<div class="row">
						<div class="col-md-3">
							<i class="material-icons md-36">notifications</i>
						</div>
						<div class="col-md-9 align-self-center text-right">
							<h5>Try & Buy Date: <%= DateTime.parse(order.created_at.to_s).strftime("%a %d %b %Y") %> </h5>	
						</div>
					</div>
					
					<hr>

					<div class="row mt-2">
							<% order.items.each do |item| %>
								<div class="col-md-3">
									<%= image_tag item.product.main_img.url, class: "img-fluid" %>
								</div>	
							<% end %>
					</div>
					
					<hr>

					<div class="row">
						<div class="col-md-12">
							<p><strong>Order Status: <%= order.order_msg %> </strong></p>	
						</div>
					</div>
					
				</div>
			</div>
		
		<% end %>
	<% end %>

</div>

<!-- ======================= Instant Try & Buy List ======================= -->

<!-- ======================= Custom Try & Buy List ======================= -->

<div class="row">
	<div align="left" class="col-md-8">
		<h1 class="brands_top_margin">Custom Try & Buy Orders</h1>		
	</div>
</div>

<hr>

<div class="row mb-5">
	
	<% @custom_orders.each do |custom_order| %>
		<% if current_user.email == custom_order.email %>	
			
			<div class="col-md-4 mt-3">
				<div class="outerbox_orderlist p-3">
					
					<div class="row">
						<div class="col-md-3">
							<i class="fa fa-<%= custom_order.order_icon %>">	</i>
						</div>
						<div class="col-md-9 align-self-center text-right">
							<h5>Try & Buy Date: <%= DateTime.parse(custom_order.created_at.to_s).strftime("%a %d %b %Y") %> </h5>	
						</div>
					</div>
				
					<hr>

					<div class="row">
						<div class="col-md-12">
							<p><strong>Order Status: <%= custom_order.order_msg %> </strong></p>	
						</div>
					</div>
					
				</div>
			</div>
		
		<% end %>
	<% end %>

</div>

<!-- ======================= Custom Try & Buy List ======================= -->


<%= render 'layouts/footer' %>

app/views/orders/new.html.erb
<div class="row brands_top_margin">
	<div class="col-md-12">
		<h3 align="center">Enter Delivery Details</h3>
	</div>
</div>

<hr>

<div class="row mt-5">

	<div class="col-md-12">
		
		<%= form_for @order, url: checkout_path, :html => {class:"form"} do |f| %>	


			<div class="row">
				<div class="col-md-6">
					
						<div class="row">
							<div class="col-md-12">
								<div class="form-group">
									<%= f.label :name %>
									<%= f.text_field :name, class: "form-control" %>
								</div>
							</div>
						</div>
					
					<div class="row">
						<div class="col-md-12">
							<div class="form-group">
								<%= f.label :email %>
								<%= f.email_field :email, class: "form-control", readonly: "true" %>
							</div>		
						</div>
					</div>

				</div>
			
				<div class="col-md-6">
					<div class="row">
						<div class="col-md-12">
							<div class="form-group">
								<%= f.label :street, "Street*" %>
								<%= f.text_field :street, class: "form-control" %>
							</div>
						</div>
					</div>

					<div class="row">
					
						<div class="col-md-6">
							<div class="form-group">
								<%= f.label :door %>
								<%= f.text_field :door, class: "form-control" %>
							</div>
						</div>

						<div class="col-md-6">
							<div class="form-group">
								<%= f.label :city %>
								<%= f.text_field :city, class: "form-control" %>
							</div>
						</div>

					</div>

				<div class="row">
					
					<div class="col-md-6">
						<div class="form-group">
							<%= f.label :zipcode %>
							<%= f.text_field :zipcode, class: "form-control" %>
						</div>
					</div>

					<div class="col-md-6">
						<div class="form-group">
							<%= f.label :phone, "Mobile Number*" %>
							<%= f.text_field :phone, class: "form-control" %>
						</div>
					</div>

				</div>	


				</div>

			</div>
			
			<hr>
			
			<div class="row">

				<div class="col-md-6">
					<p>Remember, you do not have to pay anything for the trying out the products. We will charge you only if you decide to buy something.</p>
				</div>

				<div class="col-md-3">
					<div class="form-group">
						<%= link_to "Back To Cart", order_items_path, class: "btn btn-block btn-lg btn-drop" %>
					</div>		
				</div>

				<div class="col-md-3">
					<div class="form-group">
						<%= f.submit "Checkout", class: "btn btn-block btn-lg btn-drop" %>
					</div>		
				</div>
			</div>
			
		<% end %>	

	</div>

</div>