config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'pages/home'
  root 'pages#home'
  get '/store', to: 'pages#store'
  get '/working', to: 'pages#working'
  get '/terms', to: 'pages#terms'
  get '/privacy', to: 'pages#privacy'
  get '/cfstore', to: 'pages#cfstore'
  get '/cfindex', to: 'pages#cfindex'

  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'

  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'

  get '/dashboard', to: 'orders#index', as: :dashboard

  resources :brands
  resources :products
 	resources :custom_orders

  resources :conversations do
    resources :messages
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
	mount_uploader :image, ImageUploader
end

app/models/conversation.rb
class Conversation < ApplicationRecord
	belongs_to :sender, :foreign_key => :sender_id, class_name: 'User' 
	belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User' 

	has_many :messages, dependent: :destroy 
	validates_uniqueness_of :sender_id, :scope => :recipient_id

	scope :between, -> (sender_id, recipient_id) do 
		where ("(conversations.sender_id = ? AND conversations.recipient_id =?)
		OR (conversations.sender_id = ? AND conversations.recipient_id =?)"),
	 	sender_id,recipient_id, recipient_id, sender_id
	end
end

app/models/custom_order.rb
class CustomOrder < ApplicationRecord
	  validates :name, presence: true, length: { minimum:3, maximum:50 }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :items, class_name: 'OrderItem'

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :main_img, ImageUploader
	mount_uploader :img1, ImageUploader
	mount_uploader :img2, ImageUploader
	mount_uploader :img3, ImageUploader
	mount_uploader :img4, ImageUploader
	mount_uploader :img5, ImageUploader

	def self.cat_select(category)
		where("category = ?", category)
	end

	scope :cf, -> { where(brand: "Compania Fantastica") }


end

app/models/shopping_cart.rb
class ShoppingCart

  def initialize(token:)
    @token = token
  end

  def order
    @order ||= Order.find_or_create_by(token: @token) do |order|
      order.sub_total = 0
    end
  end

  def items_count
    order.items.sum(:quantity)
  end

  def add_item(product_id:, quantity: 1)
    product = Product.find(product_id)

    order_item = order.items.find_or_initialize_by(
      product_id: product_id
    )

    order_item.price = product.price
    order_item.quantity = quantity

    order_item.save
    update_sub_total!
  end

  def remove_item(id:)
    order.items.destroy(id)
    update_sub_total!
  end

  private

    def update_sub_total!
      order.sub_total = order.items.sum('price*quantity')
      order.save
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

	 def self.new_with_session(params, session)
	  super.tap do |user|
	    if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
	      user.email = data["email"] if user.email.blank?
	    end
	  end
	end

	def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0,20]
	    user.name = auth.info.name   # assuming the user model has a name
	    user.image = auth.info.image # assuming the user model has an image
	  end
	end        

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :current_cart

  def current_cart
    @current_cart ||= ShoppingCart.new(token: cart_token)
  end
  helper_method :current_cart

  private

  def cart_token
    return @cart_token unless @cart_token.nil?

    session[:cart_token] ||= SecureRandom.hex(8)
    @cart_token = session[:cart_token]
  end


end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
	def index
		@brands = Brand.all
	end

	def create
    @brand = Brand.new(brand_params)
	  @brand.save
  end
	
	private
		def brand_params
	      params.require(:brand).permit(:name, :image)
	  end

end

app/controllers/conversations_controller.rb
class ConversationsController  < ApplicationController
	before_action :authenticate_user!

	def index
		@users = User.all
		@conversations = Conversation.all
	end

	def create
    if Conversation.between(params[:sender_id], params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end
    redirect_to conversation_messages_path(@conversation)
  end

  private
  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action do
    @conversation = Conversation.find(params[:conversation_id])
  end

  def index
    @messages = @conversation.messages
    @message = @conversation.messages.new
  end
  def new
    @message = @conversation.messages.new
  end

  def create
    @message = @conversation.messages.new(message_params)
    if @message.save
      redirect_to conversation_messages_path(@conversation)
    end
  end
  private
  def message_params
    params.require(:message).permit(:body, :user_id)
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  def index
    @items = current_cart.order.items
  end

  def create
    current_cart.add_item(
      product_id: params[:product_id],
      quantity: params[:quantity]
    )

    redirect_to cart_path
  end

  def destroy
    current_cart.remove_item(id: params[:id])
    redirect_to cart_path
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :authenticate_user!

	def index
		@orders = Order.all
		@custom_orders = CustomOrder.all
		@users = User.all
	end

	def new
		@order = current_cart.order
		@order.name = current_user.name
		@order.email = current_user.email
	end

	def create
		@order = current_cart.order

		if @order.update(order_params)
			session[:cart_token] = nil
			redirect_to dashboard_path
		else
			redirect_to 'new'
		end	
	end

	private

		def order_params
			params.require(:order).permit(:name, :street, :door, :city, :zipcode, :phone, :order_icon, :order_msg, :email)			
		end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def store
  end

  def cfstore
  end

  def cfindex
    @products = Product.cf.cat_select(params[:category]).group_by(&:title)
  end

  def terms
  end

  def privacy
  end

  def working
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :set_product, only: [:show, :edit, :update, :destroy]

	def index
		@products = Product.cat_select(params[:category]).group_by(&:title)
	end

	def new
		@product = Product.new
	end

	def create
    @product = Product.new(product_params)
	  @product.save
  end

  def show
  	@products = Product.all
  end
	
	private
		
    def set_product
      @product = Product.find(params[:id])  
    end	


		def product_params
	      params.require(:product).permit(:title, :description, :brand, :color, :size, :main_img, :img1, :img2, :img3, :img4, :img5)
	  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container-fluid">
     <div class="row mt-3">
       
       <div class="col-md-5">
        
        <div class="row">
          <div class="col-md-12">
            <p class="align-bottom">Copyright &copy 2018 DropAlley. All rights reserved.</p>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <%= link_to "Terms of Use", terms_path %>
             &nbsp; &#9642; &nbsp;
             <%= link_to "Privacy Policy", privacy_path %>
          </div>
        </div>  
         
       </div>

       <div class="col col-md-3 offset-md-4">
          <%= mail_to "contact@dropalley.com" do %>
            <i class="fa fa-envelope"></i>
           <% end %>
           <%= link_to "https://www.facebook.com/DropAlley/", target: "_blank" do %>
            <i class="fa fa-facebook"></i>
           <% end %>
           <%= link_to "https://www.youtube.com/watch?v=8TfqL3aCGeo", target: "_blank" do %>
            <i class="fa fa-youtube"></i>
           <% end %>
           <%= link_to "https://www.instagram.com/dropalley/", target: "_blank" do %>
            <i class="fa fa-instagram"></i>
           <% end %>
       </div>
     </div> 
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light navbar-bottom-shadow">
  
  <div class="container-fluid">
  
  <%= link_to image_tag("logo.png", class:"navlogo"), root_path, class: "navbar-brand" %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      

      <%= link_to "How It Works", working_path, class: "navbar-nav ml-auto nav-link links" %>

      <% if user_signed_in? %>

        <strong><%= link_to "My Cart", order_items_path, class: "navbar-nav nav-link links" %></strong>

        
        <strong><%= link_to "Dashboard", dashboard_path, class: "navbar-nav nav-link links" %></strong>

        <%= link_to "Try & Buy Now", store_path, class: "btn btn-trial btn-lg effect-btn my-2 my-sm-0" %>
      
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link links" %>
          
      <% else %>  

        <%= link_to "Login", user_session_path, class: "btn btn-trial btn-login effect-btn my-2 my-sm-0" %>

      <% end %>  

      
        
    </div>

  </div>

</nav>

app/views/layouts/_works.html.erb
<div class="row">
  
  <div class="col-md-3">
    <%= image_tag "ht1.png", class: "img-fluid" %>

    <h1 class="the_underline mt-3" align="center">01</h1>
    <h3 align="center">Discover Products</h3>
    <h5 align="center">Select from a range of handpicked fashion products.</h5>
  </div>

  <div class="col-md-3">
    <%= image_tag "ht2.png", class: "img-fluid" %>

    <h1 class="the_underline mt-3" align="center">02</h1>
    <h3 align="center">Request Products</h3>
    <h5 align="center">Pick the time and the place that best fits your busy schedule.</h5>
  </div>

  <div class="col-md-3">
    <%= image_tag "ht3.png", class: "img-fluid" %>

    <h1 class="the_underline mt-3" align="center">03</h1>
    <h3 align="center">Relax & Wait</h3>
    <h5 align="center">Your product is brought to you at your convenience by your local AlleyCat.</h5>
  </div>

  <div class="col-md-3">
    <%= image_tag "ht4.png", class: "img-fluid" %>

    <h1 class="the_underline mt-3" align="center">04</h1>
    <h3 align="center">Try & Buy</h3>
    <h5 align="center">Try products while your AlleyCat waits outside. Buy or not, you decide.</h5>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DropAlley | Try & Buy Fashion Products | Try - Check If It Fits - Then Buy | DropAlley Try & Buy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-126736250-1"></script>
   
    <script>

      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-126736250-1');

      document.addEventListener('turbolinks:load', event => {
        if (typeof gtag === 'function') {
          gtag('config', 'UA-126736250-1', {
            'page_location': event.data.url
          });
        }
      });


    </script>

    <!-- Begin Inspectlet Asynchronous Code -->
    <script type="text/javascript">
    (function() {
    window.__insp = window.__insp || [];
    __insp.push(['wid', 536212575]);
    var ldinsp = function(){
    if(typeof window.__inspld != "undefined") return; window.__inspld = 1; var insp = document.createElement('script'); insp.type = 'text/javascript'; insp.async = true; insp.id = "inspsync"; insp.src = ('https:' == document.location.protocol ? 'https' : 'http') + '://cdn.inspectlet.com/inspectlet.js?wid=536212575&r=' + Math.floor(new Date().getTime()/3600000); var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(insp, x); };
    setTimeout(ldinsp, 0);
    })();
    </script>
    <!-- End Inspectlet Asynchronous Code -->


    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render 'layouts/navigation' %>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/pages/cfindex.html.erb
<div class="row brands_top_margin">
	<div class="col col-md-12">
		<h1 align="center" class="mt-3">Products For Instant Try & Buy</h1>		
	</div>
</div>

<hr>

<div class="row mt-5 mb-5">

	<% @products.map do |k, v| %>	
		<% product = v[0] %>
		<div class="col-md-4 mt-3">
			
	    <div class="hovereffect">
	        
	        <%= image_tag product.main_img.url, class: "img-fluid" %>

        	<div class="overlay">

          	<h2><%= product.title %></h2>
           	<h2>Size: <%= product.size %></h2>
           	<%= link_to "View Product", product_path(product), class:"info" %>
           	<%= link_to "Add To Cart", order_items_path(product_id: product.id, quantity:1), method: "post", class: "info" %>
        	
        	</div>
	    
	    </div>

  	</div>

  <% end %>  

</div>

<%= render 'layouts/footer' %>

app/views/pages/cfstore.html.erb
<div class="row brands_top_margin">
	<div align="center" class="col-md-12">
			
		<%= image_tag "cfstore_logo.jpg", class: "img-fluid mt-5" %>

		<h3 class="mt-3">Try & Buy your favorite Compania Fantastica clothes in a matter of a few clicks.</h3>
	</div>
</div>

<hr>

<!-- ============================ Women's Section ================================-->

<!-- ============================ Women's Section ROW1 START ============================-->

<div class="row no-gutters">
	<div class="col-md-8">

		<div class="hovereffect">
	
			<%= image_tag "cat_w_shoes.jpg", class: "img-fluid" %>
			
			<div class="overlay">
				<h1>Women's Shoes</h1>
				<%= link_to "View Shoes", cfindex_path(category: "women_shoes"), class: "info" %>
			</div>
	

		</div>
	</div>

	<div class="col-md-4">

		<div class="hovereffect">

			<%= image_tag "cat_w_dress.jpg", class: "img-fluid" %>

			<div class="overlay">
					<h1>Women's Dresses</h1>
					<%= link_to "View Dresses", cfindex_path(category: "women_dresses"), class: "info" %>
			</div>
			
		</div>

		</div>
	</div>

</div>

<!-- ============================ Women's Section ROW1 END ============================-->


<!-- ============================ Women's Section ROW2 START ============================-->

<div class="row mt-5 mb-5 no-gutters">
	<div class="col-md-4">

		<div class="hovereffect">
			<%= image_tag "cat_w_tops.jpg", class: "img-fluid" %>

			
			<div class="overlay">
				<h1>Women's Tops</h1>
				<%= link_to "View Tops", cfindex_path(category: "women_tops"), class: "info" %>
			</div>
			

		</div>
	</div>

	<div class="col-md-4">
		<div class="hovereffect">
			
			<%= image_tag "cat_w_pants.jpg", class: "img-fluid" %>

			
			<div class="overlay">
				<h1>Women's Pants</h1>
				<%= link_to "View Pants", cfindex_path(category: "women_pants"), class: "info" %>
			</div>
		

		</div>
	</div>

	<div class="col-md-4">
		<div class="hovereffect">
			
			<%= image_tag "cat_w_skirts.jpg", class: "img-fluid" %>

				<div class="overlay">
					<h1>Women's Skirts</h1>
					<%= link_to "View Skirts", cfindex_path(category: "women_skirts"), class: "info" %>
				</div>

		</div>
	</div>


</div>


<!-- ============================ Women's Section ROW2 END ============================-->

<!-- ============================ Women's Section ROW3 START ============================-->

<div class="row mt-5 mb-5 no-gutters">

	<div class="col-md-6">

		<div class="hovereffect">
			<%= image_tag "cat_w_sweaters.jpg", class: "img-fluid" %>

			
			<div class="overlay">
				<h1>Women's Sweaters & Knitwear</h1>
				<%= link_to "View Sweaters", cfindex_path(category: "women_sweaters"), class: "info" %>
			</div>
		

		</div>
	</div>


	<div class="col-md-6">
		<div class="hovereffect">
			
			<%= image_tag "cat_w_jumpsuits.jpg", class: "img-fluid" %>

			
			<div class="overlay">
				<h1>Women's Jumpsuits</h1>
				<%= link_to "View Jumpsuits", cfindex_path(category: "women_jumpsuits"), class: "info" %>
			</div>
			

		</div>
	</div>


</div>




<!-- ============================ Women's Section ROW3 END ============================-->

<!-- ============================ Women's Section END ============================-->

<%= render 'layouts/footer' %>

app/views/pages/home.html.erb
<div class="row home_top_margin">
  <%= image_tag("1_1.jpg", :class => "col col-md-4 column_width_manager d-none d-sm-block col-sm-4") %>  
  <%= image_tag("1_3.jpg", :class => "col col-md-4 column_width_manager") %>
  <%= image_tag("2_1.jpg", :class => "col col-md-4 column_width_manager d-none d-sm-block col-sm-4") %>
</div>

<div class="row">
  <div class="col-md-8 offset-md-2">
    <h1 align="center" class="mt-3"><strong>DropAlley</strong></h1>
    <h4 align="center">We combine online and offline retail to give you the most convenient shopping experience - <strong> Try & Buy </strong>. We bring products to you whenever and wherever you want so you can TRY before you BUY.</h4>
  </div>
</div>

<div class="row mt-3">

  <div align="center" class="col-md-4 offset-md-4">
    <i class="material-icons md-48">expand_more</i>
  </div>

</div>

<!-- =================================================================================== -->

<div class="row mt-5 mb-5 no-gutters">
  <div class="col-md-6">

    <h3 align="center" class="mb-3"><strong>Try & Buy Today</strong></h3>

    <hr>

    <div class="hovereffect">
      <%= image_tag "menu_tb.jpg", class: "img-fluid" %>

      
      <div class="overlay">
        <h1>Instant craving? Fashion emergency? Check out hand-picked products available for SAME day Try & Buy.</h1>
        <%= link_to "Try & Buy Now", store_path, class: "info" %>
      </div>
    

    </div>
  </div>


  <div class="col-md-6">

    <h3 align="center" class="mb-3"><strong>NextDay+ Try & Buy</strong></h3>

    <hr>

    <div class="hovereffect">  
      <%= image_tag "menu_custom.jpg", class: "img-fluid" %>

      
      <div class="overlay">
        <h1>Busy schedule? Select products from ANY of your favorite brands to Try & Buy at your convenience.</h1>
        <%= link_to "Try & Buy",new_custom_order_path, class: "info" %>
      </div>
      

    </div>
  </div>


</div>



<!-- =================================================================================== -->

<div class="row mt-5 mb-5">
  <div class="col col-md-12">
    <h2 class="the_underline mt-3" align="center"><strong>How It Works</strong></h2>
  </div>
</div>

<%= render 'layouts/works' %>


<% if user_signed_in? %>        
    
    <div class="row mt-5 mb-5">
       <div class="col col-md-8 offset-md-2">
         <div class="outerbox_signup p-5 effect1">
           <div class="innerbox_signup">
             <h2 align="center">Welcome to DropAlley</h2>
             <h4 class="mb-5" align="center"> Your dashboard is your very own special area on the site. Click on the button below to check it out.</h4>
             <%= link_to "My Dashboard", dashboard_path, class: "btn btn-block btn-lg btn-drop" %>
           </div>
         </div>
       </div> 
    </div>

<% else %>

    <div class="row mt-5 mb-5">
       <div class="col col-md-8 offset-md-2 mt-5">
         <div class="outerbox_signup p-5 effect1">
           <div class="innerbox_signup">
             <h2 align="center">What Are You Waiting For?</h2>
             <h4 class="mb-5" align="center"> By signing up you will receive the latest updates on what products and brands you can try out before you buy.</h4>
             <%= link_to "Sign-up", new_user_registration_path, class: "btn btn-block btn-lg btn-drop" %>
           </div>
         </div>
       </div> 
    </div>

<% end %>

<%= render 'layouts/footer' %>

app/views/pages/store.html.erb
<div class="row brands_top_margin">
	<div align="center" class="col-md-12">
		<h1 class="mt-5">Welcome to the Try & Buy Today</h1>
		<h5 class="mt-3">Maybe you have an instant craving or maybe you have a fashion emergency? Either way you are at the right place. Go through our selection of handpicked products and request for a Try & Buy instantly.</h5>
	</div>
</div>

<hr>

<!-- ============================ Women's Section ================================-->

<div class="row">
	<div class="col-md-12">
		<h1 class="mt-5">Women</h1>
	</div>
</div>

<hr>

<!-- ============================ Women's Section ROW1 START ============================-->

<div class="row no-gutters">
	<div class="col-md-8">

		<div class="hovereffect">
	
			<%= image_tag "cat_w_shoes.jpg", class: "img-fluid" %>
			
			<div class="overlay">
				<h1>Women's Shoes</h1>
				<%= link_to "View Shoes", products_path(category: "women_shoes"), class: "info" %>
			</div>
	

		</div>
	</div>

	<div class="col-md-4">

		<div class="hovereffect">

			<%= image_tag "cat_w_dress.jpg", class: "img-fluid" %>

			<div class="overlay">
					<h1>Women's Dresses</h1>
					<%= link_to "View Dresses", products_path(category: "women_dresses"), class: "info" %>
			</div>
			
		</div>

		</div>
	</div>

</div>

<!-- ============================ Women's Section ROW1 END ============================-->


<!-- ============================ Women's Section ROW2 START ============================-->

<div class="row mt-5 mb-5 no-gutters">
	<div class="col-md-4">

		<div class="hovereffect">
			<%= image_tag "cat_w_tops.jpg", class: "img-fluid" %>

			
			<div class="overlay">
				<h1>Women's Tops</h1>
				<%= link_to "View Tops", products_path(category: "women_tops"), class: "info" %>
			</div>
			

		</div>
	</div>

	<div class="col-md-4">
		<div class="hovereffect">
			
			<%= image_tag "cat_w_pants.jpg", class: "img-fluid" %>

			
			<div class="overlay">
				<h1>Women's Pants</h1>
				<%= link_to "View Pants", products_path(category: "women_pants"), class: "info" %>
			</div>
		

		</div>
	</div>

	<div class="col-md-4">
		<div class="hovereffect">
			
			<%= image_tag "cat_w_skirts.jpg", class: "img-fluid" %>

				<div class="overlay">
					<h1>Women's Skirts</h1>
					<%= link_to "View Skirts", products_path(category: "women_skirts"), class: "info" %>
				</div>

		</div>
	</div>


</div>


<!-- ============================ Women's Section ROW2 END ============================-->

<!-- ============================ Women's Section ROW3 START ============================-->

<div class="row mt-5 mb-5 no-gutters">

	<div class="col-md-6">

		<div class="hovereffect">
			<%= image_tag "cat_w_sweaters.jpg", class: "img-fluid" %>

			
			<div class="overlay">
				<h1>Women's Sweaters & Knitwear</h1>
				<%= link_to "View Sweaters", products_path(category: "women_sweaters"), class: "info" %>
			</div>
		

		</div>
	</div>


	<div class="col-md-6">
		<div class="hovereffect">
			
			<%= image_tag "cat_w_jumpsuits.jpg", class: "img-fluid" %>

			
			<div class="overlay">
				<h1>Women's Jumpsuits</h1>
				<%= link_to "View Jumpsuits", products_path(category: "women_jumpsuits"), class: "info" %>
			</div>
			

		</div>
	</div>


</div>




<!-- ============================ Women's Section ROW3 END ============================-->

<!-- ============================ Women's Section END ============================-->

<!-- ============================ Men's Section =======================================-->

<div class="row">
	<div class="col-md-12">
		<h1 class="mt-5">Men</h1>
	</div>
</div>

<hr>

<!-- ============================ Men's Section ROW1 START ============================-->

<div class="row no-gutters">

	<div class="col-md-4">

		<div class="hovereffect">
			<%= image_tag "cat_m_shirts.jpg", class: "img-fluid" %>

			<div class="overlay">
				<h1>Men's Shirts</h1>
				<%= link_to "View Shirts", products_path(category: "men_shirts"), class: "info" %>
			</div>

		</div>
	</div>

	<div class="col-md-8">
		<div class="hovereffect">
			
			<%= image_tag "cat_m_shoes.jpg", class: "img-fluid" %>
			
			<div class="overlay">
				<h1>Men's Shoes</h1>
				<%= link_to "View Shoes", products_path(category: "men_shoes"), class: "info" %>
			</div>
		

		</div>
	</div>

</div>

<!-- ============================ Men's Section ROW1 END ============================-->

<!-- ============================ Men's Section ROW2 START ============================-->

<div class="row mt-5 mb-5 no-gutters">

	<div class="col-md-6">

		<div class="hovereffect">
			<%= image_tag "cat_m_sweaters.jpg", class: "img-fluid" %>

			<div class="overlay">
				<h1>Men's Sweaters & Knitwear</h1>
				<%= link_to "View Sweaters", products_path(category: "men_sweaters"), class: "info" %>
			</div>

		</div>
	</div>

	<div class="col-md-6">
		<div class="hovereffect">
			
			<%= image_tag "cat_m_jackets.jpg", class: "img-fluid" %>

			<div class="overlay">
				<h1>Men's Jackets</h1>
				<%= link_to "View Jackets", products_path(category: "men_jackets"), class: "info" %>
			</div>

		</div>
	</div>


</div>


<!-- ============================ Custom Section =======================================-->

<div class="row">
	<div class="col-md-12">
		<h1 class="mt-5">Custom Try & Buy</h1>
	</div>
</div>

<hr>

<!-- ============================ Men's Section ROW1 START ============================-->

<div class="row mb-5">

	<div class="col-md-6">

		<div class="hovereffect">
			<%= image_tag "custom.jpg", class: "img-fluid" %>

			<div class="overlay">
				<h1>Custom Try & Buy</h1>
				<%= link_to "Request Your Custom Try & Buy Now", new_custom_order_path, class: "info" %>
			</div>

		</div>
	</div>

	<div class="col-md-6">
		<h3>If you can't find anything you like but still want to try and buy, just put in a custom try & buy request. All you have to do is copy and paste the links of the products you want to try & buy and we'll get them for you.</h3>
	</div>

</div>

<!-- ============================ Men's Section ROW1 END ============================-->



<%= render 'layouts/footer' %>

app/views/pages/working.html.erb
<div class="row home_top_margin mb-5">
	<div class="col col-md-12">
    <h2 class="mt-3" align="center"><strong>How It Works</strong></h2>
  </div>
</div>

<%= render 'layouts/works' %>